version: '3'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    networks:
      - jenkins
    volumes:
      - ./certs/client:/certs/client
      - ./var/jenkins_home:/var/jenkins_home
    ports:
      - 2376:2376
      - 3000:3000
      - 5000:5000
    env_file:
      - env/docker.env
    privileged: true
    command: --storage-driver=overlay2
    restart: unless-stopped

  jenkins:
    build: .
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - ./certs/client:/certs/client:ro
      - ./var/jenkins_home:/var/jenkins_home
    ports:
      - 9000:8080
      - 50000:50000
    env_file:
      - env/jenkins.env
    restart: unless-stopped
    external_links:
      - jenkins-docker:docker

networks:
  jenkins:
    driver: bridge
