version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - ./certs/client:/certs/client:ro
      - ./var/jenkins_home:/var/jenkins_home
    ports:
      - 9000:8080
      - 50000:50000
    env_file:
      - env/jenkins.env
    restart: unless-stopped
    # external_links:
    #   - jenkins-docker:docker

  cockpit-relay:
    image: alpine/socat
    container_name: cockpit-relay
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    ports:
      - 2375:2376
    restart: unless-stopped
  # jenkins-docker:
  #   image: docker:dind
  #   container_name: jenkins-docker
  #   networks:
  #     - jenkins
  #   volumes:
  #     - ./certs/client:/certs/client
  #     - ./var/jenkins_home:/var/jenkins_home
  #   ports:
  #     - 2376:2376
  #     - 3001:3000
  #     - 5001:5000
  #   env_file:
  #     - env/docker.env
  #   privileged: true
  #   command: --storage-driver=overlay2
  #   restart: unless-stopped


  # jenkins-agent:
  #   build:
  #     context: ./
  #     dockerfile: AgentDockerfile
  #   container_name: jenkins-agent
  #   networks:
  #     - jenkins
  #   ports:
  #     - 4444:22
  #   env_file:
  #     - env/agent.env

networks:
  jenkins:
    driver: bridge
